# -*- coding: utf-8 -*-
# vim: ft=yaml
---
grafana:
  version: '6.2.2'
  pkg:
    name: grafana
    binary: grafana
    use_upstream_archive: False
    archive:
      name: /opt
      uri: https://dl.grafana.com/oss/release
      source: None
      source_hash: None
      trim_output: True   {# works in 2018.3.2. onwards #}
      archive_suffix: tar.gz
      archive_format: tar
      enforce_toplevel: True
  pkgrepo: {}
  group: grafana
  config_file: /etc/grafana/grafana.ini
  config: {}
  environ_file: /etc/default/grafana.sh
  environ: []
  service:
    name: grafana-server
    user: grafana
    group: grafana
